print("Assandra Julyant Firdausy")
print(312210368)

# luas dan keliling lingkaran
d = float(input("masukan diameter lingkaran :")) 
r = (d/2)
phi = 3.14
L = phi *(r*r)
K = (phi*d)
print("diketahui :")
print("diameter =",d,"cm")
print("jari-jari",r,"cm")
print("phi =",phi)
print("ditanya luas lingkaran dan keliling lingkaran ?")
print(" 1 = phi x r x r ")
print(" L =",phi," x ",r," x ",r)
print(" K = phi x d")
print(" K = ",phi," x ",d)
print("luas lingkaran adalah = ",L,"cm")
print("keliling lingkaran adalah :",K,"cm")